### ISSUE TITLE
Parse game configuration

### ISSUE THREAD

**Issue by Janne252** [ryantaylor/vault#3]
Hey, did you ever look into parsing the game settings?

The in-game display of a replay shows these details:
![image](https://user-images.githubusercontent.com/4705573/94580654-d5befe00-0282-11eb-96cc-dc53d5143baf.png)
- "Mod" (Tuning pack)
- Starting resources
- Starting positions
- Win condition
- Cold tech

**Comment by ryantaylor** [comment]
I think the mod is parsed, but the rest aren't. This shouldn't be very tricky though, I'll just have to collect some replays with various settings combinations. I'll take a look this week.

**Comment by Janne252** [comment]
I've made some progress with parsing various parts of the SDSC chunk: music, .sceneref stuff, atmosphere options (legacy stuff rom CoH1), minimap width & height, win condition-ish (GUID, not sure what comes after `:`), minimap layers (groups of x, y, icon path), and default skins. I've been running tests against collections of about 1k and 13k valid replays. So far so good. 

In attempt to figure out where game settings are stored, I've prepared a pretty good data set of replays. 

If we can talk on Steam or Discord, please let me know.

**Comment by ryantaylor** [comment]
Closing this because we're in CoH3 land now and I'm not gonna be adding anything to the CoH2 parser anymore unfortunately. We can discuss the CoH3 version of this if and when it comes up!
