### ISSUE TITLE
Documents on structure of replay file

### ISSUE THREAD

**Issue by Durendal** [ryantaylor/vault#4]
Hey man, love this tool. It occurred to me that I could potentially construct my own replay files and have the game engine play them out. Do you have any documentation on the actual structure of the replay file?

**Comment by ryantaylor** [comment]
Very late here, unfortunately documentation doesn't really exist for CoH replays. I've tried getting some from Relic for a long time now and haven't gotten anywhere. So unfortunately, there's a lot about replay files that is very opaque, and reverse engineering even the parseable bits is a challenge.
